### ISSUE TITLE
Issue with spawning child process

### ISSUE THREAD

**Issue by plumcraft** [ianperrin/MMM-NetworkScanner#3]
Hi,

I have the following issue with the module : 

`TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:380:9)
    at sudo (/root/MagicMirror/modules/mmm-networkscanner/node_modules/sudo/lib/sudo.js:30:17)
    at Class.scanNetwork (/root/MagicMirror/modules/mmm-networkscanner/node_helper.js:33:19)
    at Class.socketNotificationReceived (/root/MagicMirror/modules/mmm-networkscanner/node_helper.js:24:18)
    at Socket.<anonymous> (/root/MagicMirror/modules/node_modules/node_helper/index.js:98:10)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at /root/MagicMirror/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

Thanks

**Comment by derek7467** [comment]
You run the install exactly as stated?  I did on the newest Jesse IMG and it works fine out of the box. You try removing and reinstalling the module?
